ShopApp.WebUI/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ShopApp.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")] // program.cs'teki area:exists kısmı ile eşleşir.
    [Authorize(Roles = "Admin")] // Claimlerdeki claimTypes.Role ile paralel çalışır. Admin olmayanlar bu controller'dan cevap alamaz.
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ShopApp.WebUI/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Dtos;
using ShopApp.Business.Services;
using ShopApp.WebUI.Models;
using System.Security.Claims;

namespace ShopApp.WebUI.Controllers
{
    // Authentication and Authorization
    // (Kimlik Doğrulama - Yetkilendirme)
    public class AuthController : Controller
    {
        private readonly IUserService _userService;

        public AuthController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        [Route("KayitOl")]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [Route("KayitOl")]
        public IActionResult Register(RegisterViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                return View(formData);
            }

            var userAddDto = new UserAddDto()
            {
                FirstName = formData.FirstName.Trim(),
                LastName = formData.LastName.Trim(),
                Email = formData.Email.Trim(),
                Password = formData.Password
            };

            var result = _userService.AddUser(userAddDto);

            if (result.IsSucceed)
            {

                TempData["SuccessMessage"] = result.Message;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.ErrorMessage = result.Message;
                return View(formData);
            }

        }

        [HttpGet]
        [Route("GirisYap")]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [Route("GirisYap")]
        public async Task<IActionResult> Login(LoginViewModel formData)
        {
            if(!ModelState.IsValid) 
            {
                return RedirectToAction("Index", "Home");
            }

            var loginDto = new UserLoginDto()
            {
                Email = formData.Email,
                Password = formData.Password
            };

            var userInfo = _userService.LoginUser(loginDto);

            if(userInfo is null)
            {
                // Uyarı mesajı verilebilir(eklenebilir).
                return RedirectToAction("Index", "Home");
            }

            // Buraya kadar geldiyse demek ki oturum açabilirim.

            var claims = new List<Claim>();

            claims.Add(new Claim ("id" , userInfo.Id.ToString()));
            claims.Add(new Claim ("email" , userInfo.Email));
            claims.Add(new Claim ("firstName" , userInfo.FirstName));
            claims.Add(new Claim ("lastName" , userInfo.LastName));
            claims.Add(new Claim ("userType" , userInfo.UserType.ToString()));

            // Yetkilendirme (Authorization için) gerekli olan alttaki kod
            claims.Add(new Claim(ClaimTypes.Role, userInfo.UserType.ToString())); // ClaimTypes.Role -> .Net içerisinde Authorization mekanizması ile paralel çalışacak.

            var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var autProperties = new AuthenticationProperties
            {
                AllowRefresh = true,
                ExpiresUtc = new DateTimeOffset(DateTime.Now.AddHours(48))
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity), autProperties);

            TempData["SuccessMessage"] = "Kullanıcı girişi yapıldı.";

            return RedirectToAction("Index", "Home");
        }


        [Route("CikisYap")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            TempData["SuccessMessage"] = "Oturum Sonlandırıldı.";
            return RedirectToAction("Index", "Home");
        }
    }
}

ShopApp.WebUI/Views/Shared/Partials/_FlexAccordionPartial.cshtml
<link href="~/css/flexaccordion.css" rel="stylesheet" />

<div class="showcase">
    <div class="games">
        <div class="game">
            <h3>Hogwarts Legacy</h3>
        </div>
        <div class="game">
            <h3>The Legend of Zelda: Tears of the Kingdom</h3>
        </div>
        <div class="game">
            <h3>Call of Duty: Modern Warfare 3</h3>
        </div>
        <div class="game">
            <h3>Baldur's Gate 3</h3>
        </div>
        <div class="game">
            <h3>World of Warcraft: The War Within</h3>
        </div>
    </div>
</div>

ShopApp.WebUI/Views/Shared/Partials/_FooterPartial.cshtml
<footer class="bg-dark text-white text-center fw-bold py-3 mt-auto">

    2024 | Shop App
    <hr />
    <p class="text-secondary">Tüm hakları Oğuzkağan Fındık'a aittir.</p>

</footer>

ShopApp.WebUI/Views/Shared/Partials/_HeaderPartial.cshtml
<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none fw-bold">
                Shop App
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            </ul>

            <div id="login" class="d-none">
                @*display:none*@
                <partial name="Partials/_LoginPartial" model="new LoginViewModel()" />
                @* Eğer Partial View bir model alıyorsa, mutlaka boş bir modelle açılmalı. Aksi taktirde RenderBody'e gönderilen modeller buraya gönderilmiş gibi düşünülüp eşleşmeme hatası alınabilir. *@
            </div>

            @if (!User.IsLogged())
            {
                <div id="welcome">
                    <partial name="Partials/_WelcomePartial" />
                </div>
            }
            else
            {
                var firstName = User.GetUserFirstName();
                var lastName = User.GetUserLastName();

                <div class="d-flex">

                    @if (User.IsAdmin())
                    {
                        <div class="ms-3 me-3">
                            <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index" class="btn" id="AdminPanelLink">Yönetim Paneli</a>
                        </div>
                    }

                    <div class="fw-bold fst-italic mt-2">
                        Hoş Geldin @firstName @lastName
                    </div>

                    <a asp-controller="Auth" asp-action="Logout" class="btn btn-outline-warning ms-3 fw-bold">Çıkış Yap</a>
                </div>
            }

        </div>
    </div>
</header>

ShopApp.WebUI/Views/Shared/Partials/_WelcomePartial.cshtml
<div class="text-end">
    @* <button id="btnGirisYap" type="button" class="btn btn-outline-light me-2 fw-bold">Giriş</button> *@
    <a asp-controller="Auth" asp-action="Login" class="btn btn-warning fw-bold">Giriş</a>
    <a asp-controller="Auth" asp-action="Register" class="btn btn-warning fw-bold">Kayıt Ol</a>
</div>

@*
    PartialView lar büyük View yapılarını daha küçük bileşenlere ayırmanın etkili bir yoludur. View yapısının içerisinin gereksiz yere karmaşık veya büyük hale gelmesinin önüne geçebilir. Eğer kullanacağınız View yapısı oldukça karmaşık kod düzeni içeriyorsa bunu PartialView'lara bölerek kod karmaşasından kurtarabilirsiniz.

    ek ->  Aynı html kodlarından birden fazla yerde basılacaksa, partial view üzerinden çağırılabilir. (Tıpkı metot mantığı)
*@